### ISSUE TITLE
Envie de donner un coup de main

### ISSUE THREAD

**Issue by Ethsan** [info-telecom-strasbourg/InsidePSBS#14]
J'ai bien envie de donner un coup de main mais le git a l'air dans un sale état. J'ai deux questions :
- Pourquoi la branche main ne compile pas ( manque google-services.json ) ?
- Pourquoi il y a deux branches builds ?

**Comment by gatienc** [comment]
La branch main ne compile pas justement car il manque le google-services.json, actuellement l'app n'a pas était pensé pour pouvoir être compilé en local car l'accès au données nécessite des secrets ( clé API) qu'on ne peut pas partager,
si t'es chaud pour donner un coup de mail on peut voir pour ou t'inviter dans le circuits de développement ou permettre à l'app de se build en local en donnant par défauts des accès à une BDD de test. (on peut en discuter sur le discord d'ITS)

Il y a deux branches builds, une pour iOs et une pour android car il faut build les deux séparément en react-native, bien que la majorité du code soit cross-platform, des paramètres sont dépendant de la plateforme

**Comment by Ethsan** [comment]
Ok mais je ne sais pas si elles sont toujours valides mais elles ont leak sur les autres branches https://github.com/info-telecom-strasbourg/InsidePSBS/blob/build-ios/google-services.json

**Comment by gatienc** [comment]
ah mince @FelixLusseau c'est toi qui avait créer ces branches non ? si ça date de moi avant ça devrait être plus valide

**Comment by gatienc** [comment]
merci @Ethsan

**Comment by FelixLusseau** [comment]
On les avait reset non ?

**Comment by FelixLusseau** [comment]
Ah bah non.
Il va falloir les régénérer et les mettre dans le .gitignore

**Comment by FelixLusseau** [comment]
@romainbourdain ce n'est plus dans ta branche je crois tu y feras attention ;)

**Comment by Ethsan** [comment]
Après j'ai du mal à voir ce qu'il y a de secret dans le google service. Je trouve que ça rajoute une barrière en plus pour participer au projet.

**Comment by Ethsan** [comment]
A

**Comment by Ethsan** [comment]
Merci, mes questions sont répondus donc je ferme l'issue.
